version: '3.8'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - app-network

  service-b:
    build:
      context: .
      dockerfile: Dockerfile.service-b
    ports:
      - "8081:8081"
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - PORT_B=8081
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin
    networks:
      - app-network

  service-a:
    build:
      context: .
      dockerfile: Dockerfile.service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8081
      - PORT=8080
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    depends_on:
      - service-b
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
